openapi: 3.0.0
info:
  title: Test
  description: API kit router Test
  version: "1"
paths:
  /test:
    get:
      operationId: GET Test
      description: API kit get test
      responses:
        "200":
          description: This is get test
    post:
      operationId: POST Test
      description: API kit post test
      responses:
        "201":
          description: This is post test
    put:
      operationId: PUT Test
      description: API kit put test
      responses:
        "200":
          description: This is put test

    delete:
      operationId: DELETE Test
      description: API kit delete test
      responses:
        "200":
          description: This is delete test